# Generated by Django 2.2.7 on 2019-12-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Correopersonal',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correoucab',
            field=models.CharField(max_length=45),
        ),
    ]
