# Generated by Django 2.2.7 on 2019-12-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0002_auto_20191217_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombretipo', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusuarios.Tipo'),
        ),
    ]
