# Generated by Django 2.2.7 on 2019-12-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0005_statuspropuesta_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=12)),
                ('Fechaentrega', models.DateField()),
                ('Titulo', models.CharField(max_length=60)),
                ('Estatusvalor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusuarios.Statuspropuesta')),
            ],
        ),
    ]
