# Generated by Django 2.2.7 on 2019-12-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0006_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correoucab',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
