# Generated by Django 2.2.7 on 2019-12-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0007_auto_20191218_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Persona',
        ),
    ]
