# Generated by Django 2.2.7 on 2019-12-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0008_auto_20191226_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='Termpropuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusuarios.Term'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='Codigo',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
