# Generated by Django 2.2.7 on 2020-01-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0009_auto_20191230_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='Alumnouno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusuarios.Persona'),
        ),
    ]
