# Generated by Django 2.2.7 on 2020-01-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0010_propuesta_alumnouno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='Alumnouno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to='gestionusuarios.Persona'),
        ),
    ]
