# Generated by Django 2.2.7 on 2020-01-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0012_auto_20200106_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statustrabajogrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estatustg', models.CharField(max_length=27)),
            ],
        ),
    ]
