# Generated by Django 2.2.7 on 2020-01-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuarios', '0014_trabajogrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajogrado',
            name='Estatustrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusuarios.Statustrabajogrado'),
        ),
    ]
